### ISSUE TITLE
main.tf for PostgreSQL points to https://registry.terraform.io/modules/Azure/postgresql/azurerm/2.1.0 which is outdated.

### ISSUE THREAD

**Issue by annerisas** [sassoftware/viya4-iac-azure#248] opened 2022-08-02 13:36 UTC
Is it possible to have something updated in order to have the TF deploy an Azure PostgreSQL version 12 (flexible) instead of 11 (single)?
Maybe with the necessary extensions installed after deploying the PostgreSQL.

**Comment by thpang** [comment] 2022-08-02 13:51
This is targeted to be in Sprint 15 for the IAC team. Which will be Aug. 17th. This is also a duplicate of issue #79 and PR #220

**Closed by thpang** 2022-08-02 13:51 UTC
Labels: duplicate
